### ISSUE TITLE
Won't work with 'DD/MM/YYYY' format

### ISSUE THREAD

**Issue by ruslankonev** [hyiso/vue-simple-datepicker#1]
In cyrillic date format, datepicker will not work:

![not formatting](https://api.monosnap.com/rpc/file/download?id=zUzox5uT4H3SKMJUq6lFC3ZttWpIUu)

```html
<simple-datepicker
       :value.sync="startDate"
       :shown.sync="shown"
       class="form-control"
       format="DD/MM/YYYY">
</simple-datepicker>
```

**Comment by hyiso** [comment]
Sorry for late.
The given format 'DD/MM/YYYY' is just not supported by `new Date()` or `Date.parse()`, now I've added some code to get the format supported.
You can try the new version 1.0.9. :P
